spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "spin-hello-world"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "hello.wasm"
description = "A simple component that returns hello."
allowed_outbound_hosts = ["https://*:*"]
[component.hello.build]
command = "make"
watch = ["src/**/*.rs", "Cargo.toml"]
